[package]
name = "burst-core-pal-linux"
version = "0.1.0"
authors = ["Brian Anderson <banderson@mozilla.com>"]

[dependencies]
burst-alloc = { path = "../burst-alloc" }
log = { version = "0.3.5", default-features = false }
