[package]
name = "burst-core"
version = "0.1.0"
authors = ["Brian Anderson <banderson@mozilla.com>"]

[dependencies]
burst-core-pal-linux = { path = "../burst-core-pal-linux" }
log = { version = "0.3.5", default-features = false }
