[package]
name = "burst-pal-linux"
version = "0.1.0"
authors = ["Brian Anderson <banderson@mozilla.com>"]

[dependencies]
burst-core = { path = "../burst-core" }
log = { version = "0.3.5", default-features = false }
